version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  minio:
    image: "minio/minio:RELEASE.2019-06-04T01-15-58Z"
    restart: unless-stopped
    logging: *default-logging
    command: "server /data"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-12345}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-12345678}
    volumes:
      - "/data/minio:/data"
      - "/data/minioconfig:/root/.minio"
    networks:
      - default
    labels:
      - "traefik.backend=minio"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - ${MINIO_URL_CONFIG:-traefik.frontend.rule=Host:testxc-minio.naturalis.nl}

  traefik:
    image: traefik:1.7.12
    restart: always
    logging: *default-logging
    ports:
      - 8080:80
      - 8443:443
    networks:
      - default
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
      - /etc/letsencrypt:/etc/letsencrypt

# run docker network create web before
networks:
  web:
    external: true

