version: '3'
services:
  minio:
    image: "minio/minio:RELEASE.2019-06-04T01-15-58Z"
    restart: unless-stopped
    command: "server /data"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-12345}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-12345678}
    volumes:
      - "/data/minio:/data"
      - "/data/minioconfig:/root/.minio"
    networks:
      - default
    labels:
      - "traefik.backend=minio"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - ${MINIO_URL_CONFIG:-traefik.frontend.rule=Host:testxc-minio.naturalis.nl}
  traefik:
    image: traefik:1.7.12
    restart: always
    ports:
      - 8080:80
      - 8443:443
    networks:
      - default
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
      - ${ACME_JSON:-./acme.json}:/acme.json
      - /etc/letsencrypt:/etc/letsencrypt
# run docker network create web before
networks:
  web:
    external: true

